messenger4j:
  appSecret: ce1d58978254878304190d95b630ee75
  verifyToken: AzeemSalah
  pageAccessToken: EAAaIha4TIecBAGi9dY2mEBdjM5nZCeeshg8k9NRnemmKA1J28jiS9auUwZA658TihL4wgZBPYnEuEg8yt7bLfsLGpnZBJBqh7od7dZAC9ud3QryGSuXIEB2bekTvWlBQ7pqob38YqzOwNejiZAX2qHNaJtXDAvObILjNZAzQVRP7gZDZD

logging:
  level:
    com:
      github:
        messenger4j: INFO
